require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DiaHabilsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DiaHabil. As you add validations to DiaHabil, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiaHabilsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all dia_habils as @dia_habils" do
      dia_habil = DiaHabil.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dia_habils)).to eq([dia_habil])
    end
  end

  describe "GET #show" do
    it "assigns the requested dia_habil as @dia_habil" do
      dia_habil = DiaHabil.create! valid_attributes
      get :show, {:id => dia_habil.to_param}, valid_session
      expect(assigns(:dia_habil)).to eq(dia_habil)
    end
  end

  describe "GET #new" do
    it "assigns a new dia_habil as @dia_habil" do
      get :new, {}, valid_session
      expect(assigns(:dia_habil)).to be_a_new(DiaHabil)
    end
  end

  describe "GET #edit" do
    it "assigns the requested dia_habil as @dia_habil" do
      dia_habil = DiaHabil.create! valid_attributes
      get :edit, {:id => dia_habil.to_param}, valid_session
      expect(assigns(:dia_habil)).to eq(dia_habil)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DiaHabil" do
        expect {
          post :create, {:dia_habil => valid_attributes}, valid_session
        }.to change(DiaHabil, :count).by(1)
      end

      it "assigns a newly created dia_habil as @dia_habil" do
        post :create, {:dia_habil => valid_attributes}, valid_session
        expect(assigns(:dia_habil)).to be_a(DiaHabil)
        expect(assigns(:dia_habil)).to be_persisted
      end

      it "redirects to the created dia_habil" do
        post :create, {:dia_habil => valid_attributes}, valid_session
        expect(response).to redirect_to(DiaHabil.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved dia_habil as @dia_habil" do
        post :create, {:dia_habil => invalid_attributes}, valid_session
        expect(assigns(:dia_habil)).to be_a_new(DiaHabil)
      end

      it "re-renders the 'new' template" do
        post :create, {:dia_habil => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dia_habil" do
        dia_habil = DiaHabil.create! valid_attributes
        put :update, {:id => dia_habil.to_param, :dia_habil => new_attributes}, valid_session
        dia_habil.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dia_habil as @dia_habil" do
        dia_habil = DiaHabil.create! valid_attributes
        put :update, {:id => dia_habil.to_param, :dia_habil => valid_attributes}, valid_session
        expect(assigns(:dia_habil)).to eq(dia_habil)
      end

      it "redirects to the dia_habil" do
        dia_habil = DiaHabil.create! valid_attributes
        put :update, {:id => dia_habil.to_param, :dia_habil => valid_attributes}, valid_session
        expect(response).to redirect_to(dia_habil)
      end
    end

    context "with invalid params" do
      it "assigns the dia_habil as @dia_habil" do
        dia_habil = DiaHabil.create! valid_attributes
        put :update, {:id => dia_habil.to_param, :dia_habil => invalid_attributes}, valid_session
        expect(assigns(:dia_habil)).to eq(dia_habil)
      end

      it "re-renders the 'edit' template" do
        dia_habil = DiaHabil.create! valid_attributes
        put :update, {:id => dia_habil.to_param, :dia_habil => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested dia_habil" do
      dia_habil = DiaHabil.create! valid_attributes
      expect {
        delete :destroy, {:id => dia_habil.to_param}, valid_session
      }.to change(DiaHabil, :count).by(-1)
    end

    it "redirects to the dia_habils list" do
      dia_habil = DiaHabil.create! valid_attributes
      delete :destroy, {:id => dia_habil.to_param}, valid_session
      expect(response).to redirect_to(dia_habils_url)
    end
  end

end
