require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FormatoHcPreguntaController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FormatoHcPreguntum. As you add validations to FormatoHcPreguntum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FormatoHcPreguntaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all formato_hc_pregunta as @formato_hc_pregunta" do
      formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:formato_hc_pregunta)).to eq([formato_hc_preguntum])
    end
  end

  describe "GET #show" do
    it "assigns the requested formato_hc_preguntum as @formato_hc_preguntum" do
      formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
      get :show, {:id => formato_hc_preguntum.to_param}, valid_session
      expect(assigns(:formato_hc_preguntum)).to eq(formato_hc_preguntum)
    end
  end

  describe "GET #new" do
    it "assigns a new formato_hc_preguntum as @formato_hc_preguntum" do
      get :new, {}, valid_session
      expect(assigns(:formato_hc_preguntum)).to be_a_new(FormatoHcPreguntum)
    end
  end

  describe "GET #edit" do
    it "assigns the requested formato_hc_preguntum as @formato_hc_preguntum" do
      formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
      get :edit, {:id => formato_hc_preguntum.to_param}, valid_session
      expect(assigns(:formato_hc_preguntum)).to eq(formato_hc_preguntum)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FormatoHcPreguntum" do
        expect {
          post :create, {:formato_hc_preguntum => valid_attributes}, valid_session
        }.to change(FormatoHcPreguntum, :count).by(1)
      end

      it "assigns a newly created formato_hc_preguntum as @formato_hc_preguntum" do
        post :create, {:formato_hc_preguntum => valid_attributes}, valid_session
        expect(assigns(:formato_hc_preguntum)).to be_a(FormatoHcPreguntum)
        expect(assigns(:formato_hc_preguntum)).to be_persisted
      end

      it "redirects to the created formato_hc_preguntum" do
        post :create, {:formato_hc_preguntum => valid_attributes}, valid_session
        expect(response).to redirect_to(FormatoHcPreguntum.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved formato_hc_preguntum as @formato_hc_preguntum" do
        post :create, {:formato_hc_preguntum => invalid_attributes}, valid_session
        expect(assigns(:formato_hc_preguntum)).to be_a_new(FormatoHcPreguntum)
      end

      it "re-renders the 'new' template" do
        post :create, {:formato_hc_preguntum => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested formato_hc_preguntum" do
        formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
        put :update, {:id => formato_hc_preguntum.to_param, :formato_hc_preguntum => new_attributes}, valid_session
        formato_hc_preguntum.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested formato_hc_preguntum as @formato_hc_preguntum" do
        formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
        put :update, {:id => formato_hc_preguntum.to_param, :formato_hc_preguntum => valid_attributes}, valid_session
        expect(assigns(:formato_hc_preguntum)).to eq(formato_hc_preguntum)
      end

      it "redirects to the formato_hc_preguntum" do
        formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
        put :update, {:id => formato_hc_preguntum.to_param, :formato_hc_preguntum => valid_attributes}, valid_session
        expect(response).to redirect_to(formato_hc_preguntum)
      end
    end

    context "with invalid params" do
      it "assigns the formato_hc_preguntum as @formato_hc_preguntum" do
        formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
        put :update, {:id => formato_hc_preguntum.to_param, :formato_hc_preguntum => invalid_attributes}, valid_session
        expect(assigns(:formato_hc_preguntum)).to eq(formato_hc_preguntum)
      end

      it "re-renders the 'edit' template" do
        formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
        put :update, {:id => formato_hc_preguntum.to_param, :formato_hc_preguntum => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested formato_hc_preguntum" do
      formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
      expect {
        delete :destroy, {:id => formato_hc_preguntum.to_param}, valid_session
      }.to change(FormatoHcPreguntum, :count).by(-1)
    end

    it "redirects to the formato_hc_pregunta list" do
      formato_hc_preguntum = FormatoHcPreguntum.create! valid_attributes
      delete :destroy, {:id => formato_hc_preguntum.to_param}, valid_session
      expect(response).to redirect_to(formato_hc_pregunta_url)
    end
  end

end
