require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HoraHabilsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # HoraHabil. As you add validations to HoraHabil, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HoraHabilsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all hora_habils as @hora_habils" do
      hora_habil = HoraHabil.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:hora_habils)).to eq([hora_habil])
    end
  end

  describe "GET #show" do
    it "assigns the requested hora_habil as @hora_habil" do
      hora_habil = HoraHabil.create! valid_attributes
      get :show, {:id => hora_habil.to_param}, valid_session
      expect(assigns(:hora_habil)).to eq(hora_habil)
    end
  end

  describe "GET #new" do
    it "assigns a new hora_habil as @hora_habil" do
      get :new, {}, valid_session
      expect(assigns(:hora_habil)).to be_a_new(HoraHabil)
    end
  end

  describe "GET #edit" do
    it "assigns the requested hora_habil as @hora_habil" do
      hora_habil = HoraHabil.create! valid_attributes
      get :edit, {:id => hora_habil.to_param}, valid_session
      expect(assigns(:hora_habil)).to eq(hora_habil)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HoraHabil" do
        expect {
          post :create, {:hora_habil => valid_attributes}, valid_session
        }.to change(HoraHabil, :count).by(1)
      end

      it "assigns a newly created hora_habil as @hora_habil" do
        post :create, {:hora_habil => valid_attributes}, valid_session
        expect(assigns(:hora_habil)).to be_a(HoraHabil)
        expect(assigns(:hora_habil)).to be_persisted
      end

      it "redirects to the created hora_habil" do
        post :create, {:hora_habil => valid_attributes}, valid_session
        expect(response).to redirect_to(HoraHabil.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved hora_habil as @hora_habil" do
        post :create, {:hora_habil => invalid_attributes}, valid_session
        expect(assigns(:hora_habil)).to be_a_new(HoraHabil)
      end

      it "re-renders the 'new' template" do
        post :create, {:hora_habil => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hora_habil" do
        hora_habil = HoraHabil.create! valid_attributes
        put :update, {:id => hora_habil.to_param, :hora_habil => new_attributes}, valid_session
        hora_habil.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested hora_habil as @hora_habil" do
        hora_habil = HoraHabil.create! valid_attributes
        put :update, {:id => hora_habil.to_param, :hora_habil => valid_attributes}, valid_session
        expect(assigns(:hora_habil)).to eq(hora_habil)
      end

      it "redirects to the hora_habil" do
        hora_habil = HoraHabil.create! valid_attributes
        put :update, {:id => hora_habil.to_param, :hora_habil => valid_attributes}, valid_session
        expect(response).to redirect_to(hora_habil)
      end
    end

    context "with invalid params" do
      it "assigns the hora_habil as @hora_habil" do
        hora_habil = HoraHabil.create! valid_attributes
        put :update, {:id => hora_habil.to_param, :hora_habil => invalid_attributes}, valid_session
        expect(assigns(:hora_habil)).to eq(hora_habil)
      end

      it "re-renders the 'edit' template" do
        hora_habil = HoraHabil.create! valid_attributes
        put :update, {:id => hora_habil.to_param, :hora_habil => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested hora_habil" do
      hora_habil = HoraHabil.create! valid_attributes
      expect {
        delete :destroy, {:id => hora_habil.to_param}, valid_session
      }.to change(HoraHabil, :count).by(-1)
    end

    it "redirects to the hora_habils list" do
      hora_habil = HoraHabil.create! valid_attributes
      delete :destroy, {:id => hora_habil.to_param}, valid_session
      expect(response).to redirect_to(hora_habils_url)
    end
  end

end
