require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MinutosHabilesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MinutosHabile. As you add validations to MinutosHabile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MinutosHabilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all minutos_habiles as @minutos_habiles" do
      minutos_habile = MinutosHabile.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:minutos_habiles)).to eq([minutos_habile])
    end
  end

  describe "GET #show" do
    it "assigns the requested minutos_habile as @minutos_habile" do
      minutos_habile = MinutosHabile.create! valid_attributes
      get :show, {:id => minutos_habile.to_param}, valid_session
      expect(assigns(:minutos_habile)).to eq(minutos_habile)
    end
  end

  describe "GET #new" do
    it "assigns a new minutos_habile as @minutos_habile" do
      get :new, {}, valid_session
      expect(assigns(:minutos_habile)).to be_a_new(MinutosHabile)
    end
  end

  describe "GET #edit" do
    it "assigns the requested minutos_habile as @minutos_habile" do
      minutos_habile = MinutosHabile.create! valid_attributes
      get :edit, {:id => minutos_habile.to_param}, valid_session
      expect(assigns(:minutos_habile)).to eq(minutos_habile)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MinutosHabile" do
        expect {
          post :create, {:minutos_habile => valid_attributes}, valid_session
        }.to change(MinutosHabile, :count).by(1)
      end

      it "assigns a newly created minutos_habile as @minutos_habile" do
        post :create, {:minutos_habile => valid_attributes}, valid_session
        expect(assigns(:minutos_habile)).to be_a(MinutosHabile)
        expect(assigns(:minutos_habile)).to be_persisted
      end

      it "redirects to the created minutos_habile" do
        post :create, {:minutos_habile => valid_attributes}, valid_session
        expect(response).to redirect_to(MinutosHabile.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved minutos_habile as @minutos_habile" do
        post :create, {:minutos_habile => invalid_attributes}, valid_session
        expect(assigns(:minutos_habile)).to be_a_new(MinutosHabile)
      end

      it "re-renders the 'new' template" do
        post :create, {:minutos_habile => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested minutos_habile" do
        minutos_habile = MinutosHabile.create! valid_attributes
        put :update, {:id => minutos_habile.to_param, :minutos_habile => new_attributes}, valid_session
        minutos_habile.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested minutos_habile as @minutos_habile" do
        minutos_habile = MinutosHabile.create! valid_attributes
        put :update, {:id => minutos_habile.to_param, :minutos_habile => valid_attributes}, valid_session
        expect(assigns(:minutos_habile)).to eq(minutos_habile)
      end

      it "redirects to the minutos_habile" do
        minutos_habile = MinutosHabile.create! valid_attributes
        put :update, {:id => minutos_habile.to_param, :minutos_habile => valid_attributes}, valid_session
        expect(response).to redirect_to(minutos_habile)
      end
    end

    context "with invalid params" do
      it "assigns the minutos_habile as @minutos_habile" do
        minutos_habile = MinutosHabile.create! valid_attributes
        put :update, {:id => minutos_habile.to_param, :minutos_habile => invalid_attributes}, valid_session
        expect(assigns(:minutos_habile)).to eq(minutos_habile)
      end

      it "re-renders the 'edit' template" do
        minutos_habile = MinutosHabile.create! valid_attributes
        put :update, {:id => minutos_habile.to_param, :minutos_habile => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested minutos_habile" do
      minutos_habile = MinutosHabile.create! valid_attributes
      expect {
        delete :destroy, {:id => minutos_habile.to_param}, valid_session
      }.to change(MinutosHabile, :count).by(-1)
    end

    it "redirects to the minutos_habiles list" do
      minutos_habile = MinutosHabile.create! valid_attributes
      delete :destroy, {:id => minutos_habile.to_param}, valid_session
      expect(response).to redirect_to(minutos_habiles_url)
    end
  end

end
